config/routes.rb
Poker2::Application.routes.draw do
  devise_for :admins
  resources :definitions

  get 'games/random' => 'games#random'
  get 'games/calc' => 'games#calc'
  get 'games/welcome' => 'games#welcome'
  resources :games

  resources :styles
  
  root 'games#index'
  
  
  

  

end

app/models/definition.rb
class Definition < ActiveRecord::Base
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :set_definition, only: [:show, :edit, :update, :destroy]
  
  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all
  end

  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit
  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @definition }
      else
        format.html { render action: 'new' }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition
      @definition = Definition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_params
      params.require(:definition).permit(:word, :definition)
    end
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_form.html.erb
<%= form_for(@definition) do |f| %>
  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% @definition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :definition %><br>
    <%= f.text_area :definition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/definitions/edit.html.erb
<h1>Editing definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @definition %> |
<%= link_to 'Back', definitions_path %>

app/views/definitions/index.html.erb
<h1>Listing definitions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Word</th>
      <th>Definition</th>
			<th></th>
    </tr>
  </thead>

  <tbody>
    <% @definitions.each do |definition| %>
      <tr>
		<% if admin_signed_in? %>
        	<td><%= link_to definition.word, edit_definition_path(definition) %></td>
		<% else %>
			<td><%= link_to definition.word, definition_path(definition) %></td>
		<% end %>
		<td><%= definition.definition %></td>
		<% if admin_signed_in? %>
	      	<td><%= link_to 'Delete', definition, method: :delete %></td>
		<% end %>
			</tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Definition', new_definition_path %>

app/views/definitions/new.html.erb
<h1>New definition</h1>

<%= render 'form' %>

<%= link_to 'Back', definitions_path %>

app/views/definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @definition.word %>
</p>

<p>
  <strong>Definition:</strong>
  <%= @definition.definition %>
</p>

<% if admin_signed_in? %>
	<%= link_to 'Edit', edit_definition_path(@definition) %> |
<% end %>
<%= link_to 'Back', definitions_path %>