config/routes.rb
Poker2::Application.routes.draw do
  devise_for :admins
  resources :definitions

  get 'games/random' => 'games#random'
  get 'games/calc' => 'games#calc'
  get 'games/welcome' => 'games#welcome'
  resources :games

  resources :styles
  
  root 'games#index'
  
  
  

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :style
  default_scope :order => 'name'
  
  def self.search_all(queries)
    list = []
    queries.gsub(/\s+/m, ' ').strip.split(" ").each do |query|
      sublist = []
      sublist << search_name_or_description(query)
      sublist << search_style(Style.where("name @@ :q", q: query).first.id) unless Style.where("name @@ :q", q: query).empty?
      sublist << search_tags(query)
      list << "(#{sublist.join(" OR ")})"
    end
    where(list.join(" AND "))
  end

  private
  def self.search_name_or_description(query)
    "name @@ '#{query}' or description @@ '#{query}'"
  end
  
  def self.search_style(id)
    "style_id = #{id}"
  end
  
  def self.search_tags(query)
    "'#{query}' = ANY (tags)"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /welcome
  def welcome
    @games = Hash.new
    @games[:new] = Game.order(created_at: :desc).limit(5)
    @games[:updated] = Game.order(updated_at: :desc).limit(5)
    @games[:random] = Game.order("RANDOM()").limit(5)
  end
  
  # GET /games
  # GET /games.json
  def index
    @sort = {"name" => nil, "style_id" => nil, "min_players" => nil, "max_players" => nil, "num_cards" => nil}
    unless params["search"].nil?
      @games = Game.search_all(params["search"])
    else
      @games = Game.all
    end
    if params["sort_column"]
      case params["sort_direction"]
      when "ASC"
        @sort[params["sort_column"]] = "DESC"
      when "DESC"
        @sort[params["sort_column"]] = "ASC"
      else
        @sort[params["sort_column"]] = "DESC"
      end
      
    end
    params["show"] ||= 10
    params["show"] = @games.count if params["show"] == "all"
    @all_games = @games.order(sort_column + " " + sort_direction)
    @games = @games.order(sort_column + " " + sort_direction).paginate(:per_page => params["show"], :page => params[:page])
    @show = params["show"]
    @tags = tag_list
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end
  
  # GET /games/random
  def random
    @game = Game.order("RANDOM()").first
    render 'show'
  end
  
  # GET /games/calc
  def calc
    
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    game_params["tags"]=params["game"]["tags"]
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :style_id, :min_players, :max_players, :num_cards, tags: [])
    end
    
    def sort_column
      Game.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_advanced_search.html.erb
<div>
	<%= form_tag games_path, :method => 'get', :id => "advanced_search" do %>
  	<p>
    	<%= text_field_tag :search, params[:search] %>
    	<%= submit_tag "Search", :name => nil %>
  	</p>
	<% end %>
</div>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
	<body>
	<% if @game.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:
			</h2>
			<ul>
				<% @game.errors.full_messages.each do |msg| %>
					<li>
						<%= msg %>
					</li>
				<% end %>
			</ul>
		</div>
	<% end %>
		<div class="form-group">
			<%= f.label :name %><br>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :description %><br>
			<p class="help-block">Use markdown for description. <a href="#" onclick="toggle_visibility('markdown_examples');">Click here for examples</a>
			</p>
			<div id="markdown_examples" style="display: none;">
				<table class="table table-bordered table-condensed table-striped" >
					<thead>
						<th>Markdown Input</th>
						<th>Output</th>
					</thead>
					<tbody>
						<tr>
							<td># Header 1</td>
							<td><%= markdown("\# Header 1")%></td>
						</tr>
						<tr>
							<td>## Header 2</td>
							<td><%= markdown("\#\# Header 2")%></td>
						</tr>
						<tr>
							<td>### Header 3</td>
							<td><%= markdown("\#\#\# Header 3")%>
							</td>
						</tr>
						<tr>
							<td>
								* Item 1 <br/>
								* Item 2 <br/>
								* Item 3 <br/>
							</td>
							<td>
							<%= markdown("* Item 1\n* Item 2\n* Item 3")%>
							</td>
						</tr>
						<tr>
							<td>
								*italics*    _italics_
							</td>
							<td>
								<%= markdown("*italics*    _italics_")%>
							</td>
						</tr>
						<tr>
							<td>
								**bold**    __bold__
							</td>
							<td>
							<%= markdown("**bold**    __bold__")%>
							</td>
						</tr>
						<tr>
							<td>
								This is [an example](http://example.com/ "Optional Title")
								inline link.
							</td>
							<td>
							<%= markdown("This is [an example](http://example.com/ \"Optional Title\")
							inline link.")%>
							</td>
						</tr>
						<tr><td>\\</td><td><%= markdown("\\")%></td></tr>
						<tr><td>[card:ace of spades]</td><td><%= markdown("[card:ace of spades]")%></td></tr>
						<tr><td>[game:sample]</td><td><%= markdown("[game:sample]")%></td></tr>
					</tbody>
				</table>
			</div>
			<%= f.text_area :description, class: "form-control", rows: "10" %>
		</div>
		<div class="form-group">
			<%= f.label :style_id %><br>
			<%= f.collection_radio_buttons :style_id, Style.all, :id, :name, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :min_players %><br>
			<%= f.number_field :min_players, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :max_players %><br>
			<%= f.number_field :max_players, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :num_cards %><br>
			<%= f.number_field :num_cards, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :tags %><br>
			<%= f.collection_check_boxes :tags, %w[wildcard pot-matching dickish hi-lo], :to_s, :to_s, class: "form-control"%>
		</div>
		<div class="actions">
			<%= f.submit %>
		</div><% end %>
	</body>
</html>

app/views/games/calc.html.erb
<%= %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<% if params["search"] %>
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		Searching for <strong>"<%= params["search"] %>"</strong>, click <%= link_to "here", games_path(params.except("search")), :class =>"btn btn-default btn-sm" %> to clear search
	</div>
<% end %>
<h1>Listing games</h1>
<div class="row">
	<div class="col-md-9">
		Tags:
		<% @tags.each do |tag| %>
			<%= clickable_tag(tag) %>
		<% end %>
	</div>
	<div class="col-md-1">
		<div class="btn-group">
		  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		    Showing <%= @show %> Results <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" role="menu">
		    <li><%= link_to "Show 10 results", games_path(params.merge(show: "10"))%></li>
		    <li><%= link_to "Show 50 results", games_path(params.merge(show: "50"))%></li>
		    <li><%= link_to "Show all results", games_path(params.merge(show: "all"))%></li>
		  </ul>
		</div>
	</div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "style_id", "Style" %></th>
      <th><%= sortable "min_players", "Minimum # of Players"%></th>
      <th><%= sortable "max_players", "Maximum # of Players"%></th>
      <th><%= sortable "num_cards", "Number of Cards"%></th>
      <th>Tags</th>
 	  <% if admin_signed_in? %>
      	<th></th>
      	<th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
				<td><%= link_to game.name, game %></td>
        <td><%= game.style.name unless game.style.nil? %></td>
        <td><%= game.min_players %></td>
        <td><%= game.max_players %></td>
        <td><%= game.num_cards %></td>
        <td>
					<% game.tags.each do |tag| %>
						<%= clickable_tag(tag) %>
					<% end %>
				</td>
		<% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @games, renderer: BootstrapPagination::Rails, bootstrap: 3 %>

<br>


<%= link_to 'New Game', new_game_path %> | <%= link_to 'Export as JSON', games_path(:format => :json) %> | <%= link_to 'Export as CSV', games_path(:format => :csv) %><br/>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="alert-success"><p id="notice"><%= notice %></p></div>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= markdown(@game.description) %>
</p>

<p>
  <strong>Style:</strong>
  <%= @game.style.name unless @game.style.nil? %>
</p>

<p>
  <strong>Min players:</strong>
  <%= @game.min_players %>
</p>

<p>
  <strong>Max players:</strong>
  <%= @game.max_players %>
</p>

<p>
  <strong>Num cards:</strong>
  <%= @game.num_cards %>
</p>

<p>
  <strong>Tags:</strong>
  <% @game.tags.each do |tag| %>
		<%= clickable_tag(tag) %>
	<% end %>
</p>

<%= link_to 'New Game', new_game_path %> |
<% if admin_signed_in? %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<% end %>
<%= link_to 'Back', games_path %>

app/views/games/welcome.html.erb
<div class="row">
  <div class="col-md-4">
  	<div class="panel panel-info">
			<div class="panel-heading">Newest Games</div>
		  <div class="panel-body">
		    <% @games[:new].each do |game| %>
					<%= link_to game.name, game, class: "list-group-item"%>
				<% end %>
		  </div>
		</div>
  </div>
  <div class="col-md-4">
  	<div class="panel panel-info">
			<div class="panel-heading">Recently Updated Games</div>
		  <div class="panel-body">
		    <% @games[:updated].each do |game| %>
					<%= link_to game.name, game, class: "list-group-item"%>
				<% end %>
		  </div>
		</div>
  </div>
	<div class="col-md-4">
  	<div class="panel panel-info">
			<div class="panel-heading">Random Games</div>
		  <div class="panel-body">
		    <% @games[:random].each do |game| %>
					<%= link_to game.name, game, class: "list-group-item"%>
				<% end %>
		  </div>
		</div>
  </div>
</div>