config/routes.rb
Poker2::Application.routes.draw do
  devise_for :admins
  resources :definitions

  get 'games/random' => 'games#random'
  get 'games/calc' => 'games#calc'
  get 'games/welcome' => 'games#welcome'
  resources :games

  resources :styles
  
  root 'games#index'
  
  
  

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poker House</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<nav class="navbar navbar-default" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	      <span class="sr-only">Toggle navigation</span>
	    </button>
			<%= link_to "Poker House", root_path, :class =>"navbar-brand" %>
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse navbar-ex1-collapse">
	    <ul class="nav navbar-nav">
	      <li><%= link_to "Games", games_path %></li>
	      <li><%= link_to "Styles", styles_path %></li>
	      <li><%= link_to "Definitions", definitions_path %></li>
	      <li><%= link_to "Random Game", games_random_path %></li>
		  <% if admin_signed_in? %>
		    <li>
		    <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
		    </li>
		  <% else %>
		    <li>
		    <%= link_to('Login', new_admin_session_path)  %>  
		    </li>
		  <% end %>
	    </ul>
			<%= form_tag games_path, :method => 'get', :id => "games_search", :class => "navbar-form navbar-right" do %>
		    <div class="form-group">	
					<% params.each_pair do |k,v| %>
						<%= hidden_field_tag k.to_sym, v unless k.to_sym == :search %>
					<% end %>
					<%= text_field_tag :search, params[:search], :class => "form-control", :placeholder => "Search Games" %>
		    </div>
				<%= submit_tag "Search", :name => nil, :class =>"btn btn-default" %>
			<% end %>
	  </div><!-- /.navbar-collapse -->
	</nav>
	<% if alert %><div class="alert alert-danger alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<%= alert %>
	</div><% end %>
	<% if notice %><div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><%= notice %></div><% end %>

	<div class="row">
	  <div class="col-md-1"></div>
	  <div class="col-md-10">
			<%= yield %></div>
		<div class="col-md-1"></div>
	</div>

</body>
</html>